version: "3.8"

services:
  data-generator:
    build:
      context: .
      dockerfile: docker/Dockerfile.generator
    volumes:
      - ./data_generator:/app/data_generator
    environment:
      - VOTERS_COUNT=1000
      - VOTES_PER_MINUTE=100
    networks:
      - voting-network
    depends_on:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - voting-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "votes:4:1,voters:1:1"
    networks:
      - voting-network
    depends_on:
      - zookeeper

networks:
  voting-network:
    driver: bridge
