#docker/Dockerfile.ingestion
FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire app source code
COPY . .

# Set environment variables
ENV PYTHONPATH=/app

# Default command (can be overridden in docker-compose)
CMD ["python", "-m", "ingestion.dlt_pipeline.voter_pipeline"]